version: '3.8'

name: spring-app
services:
  db:
   container_name: db
   image: mysql:latest
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: 'admin123'
   ports:
   - "3306:3306"
   volumes:
   - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql